# Uncomment this line to define a global platform for your project
 platform :ios, ‘8.0’

target 'XYGenericFramework' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XYGenericFramework
 pod 'AFNetworking', '~> 3.1.0'
 pod 'SwiftyJSON', '~> 3.1.1'
 pod 'MJRefresh', '~> 3.1.12'
 pod 'SDWebImage', '~> 3.8.2'
 pod 'MBProgressHUD', '~> 1.0.0'
 pod 'FMDB', '~> 2.7.2'
 pod 'Masonry', '~> 1.0.2'
 pod 'WechatOpenSDK'
 pod "Kingfisher"
 pod 'HandyJSON', '~> 4.2.0'
 pod 'Alamofire'
 pod 'IQKeyboardManagerSwift'
 
end
